name: Acquire activation file

on:
  push: { branches: [feature/ci] }

jobs:
  activation:
    name: Request manual activation file ðŸ”‘
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Request Activation File
      uses: webbertakken/unity-request-activation-file@v1.2
      with:
        unityVersion: 2019.4.8f1

    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}